### PR TITLE
Should really fire the jQuery 'change' event also or clicking straight on

### PR DESCRIPTION
**Pull request by laurikoobas**
Should really fire the jQuery 'change' event also or clicking straight on the radio button / checkbox (instead of label) doesn't fire the event.

### CODE REVIEW

**Comment by laurikoobas** [comment]
Actually firing the 'change()' is only required for radio button. So disregard the change at checkbox.

**Comment by dciccale** [comment]
it is already fireing the native change event in both cases, no need to trigger it again, if you are having any issue on this, open a new issue,

fyi, i am working on a whole new version of the plugin, a big refactorization, with enhanced behaviour

thanks!

**Comment by laurikoobas** [comment]
Hi,

I ran into this again and it does not fire native change events. It changes
the value of the replaced, hidden item. BUT events don't fire on hidden
items. Hence the need to manually fire the change event after changing the
value.

Lauri

2011/8/29 dciccale <
reply@reply.github.com>

**Comment by dciccale** [comment]
@laurikoobas maybe this http://bugs.jquery.com/ticket/8508 is the problem that you are having.

if you are hiding the radios or checkboxes using `css display:none;` or `css visibility:hidden;` you must remove those.. and use absolute positioning and for example setting `css left:-999em;`

I saw the code you wrote and if you are trying to force the check programatically, then you should fire the change event. that's ok.

however i will not add your update to the code because i'm refactoring the code, and the force option will not be there.

also have in mind that this script does not have to manage the fireing of the real input. think if you are not using the plugin, and want to check a checkbox programatically, then you will have to fire the change event manually anyway.

**Pull request closed without merging**
